### ISSUE TITLE
Exception when running against: `https://github.com/nucypher/nucypher`

### ISSUE THREAD

**Issue by mscottford** [corgibytes/freshli#30] opened 2020-06-17 01:44 UTC
Exception from Jupyter Notebook:

```
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Freshli.Languages.Python.PyPIRepository.Latest(String name, String thatMatches, DateTime asOf)
   at Freshli.LibYearCalculator.ComputeAsOf(DateTime date)
   at Freshli.Runner.Run(String analysisPath, DateTime asOf)
   at Freshli.Runner.Run(String analysisPath)
   at Submission#20.<<Initialize>>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmissionsAsync[TResult](ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, StrongBox`1 exceptionHolderOpt, Func`2 catchExceptionOpt, CancellationToken cancellationToken)
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Freshli.Languages.Python.PyPIRepository.Latest(String name, String thatMatches, DateTime asOf)
   at Freshli.LibYearCalculator.ComputeAsOf(DateTime date)
   at Freshli.Runner.Run(String analysisPath, DateTime asOf)
   at Freshli.Runner.Run(String analysisPath)
   at Submission#20.<<Initialize>>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmissionsAsync[TResult](ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, StrongBox`1 exceptionHolderOpt, Func`2 catchExceptionOpt, CancellationToken cancellationToken)
```

**Comment by dan-hein** [comment] 2021-02-03 20:09
Hello, I could be wrong in my approach to reproduce this issue, but when I run this through my Jupyter Notebook, I am unable to reproduce this error with the current code on main. Could this have been inadvertently fixed since June 16, 2020?

<img width="1141" alt="Screen Shot 2021-02-03 at 3 05 44 PM" src="https://user-images.githubusercontent.com/5385329/106802983-ac97eb00-6631-11eb-807f-336288f48d8e.png">

**Comment by nickiemc** [comment] 2021-02-03 23:57
@dan-hein Yes, it's likely that some of the other fixes that have been merged recently have fixed this.

**Comment by dan-hein** [comment] 2021-02-04 13:49
Thanks, Nickie! I'll close this task until the issue reemerges.

**Closed by dan-hein** 2021-02-04 13:49 UTC
Labels: bug, python
